---
abstract: 'Cisco Unified Communications XML API'
author:
  - 'Oliver Gorwits C<< <oliver.gorwits@oucs.ox.ac.uk> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AXL-Client-Simple
no_index:
  directory:
    - inc
    - share
    - t
requires:
  File::ShareDir: 0
  Moose: 0
  MooseX::Iterator: 0
  URI::Escape: 0
  XML::Compile::SOAP: 0
  XML::Compile::WSDL11: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: '0.02'
